apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
      memory: "512Mi"
  restartPolicy: Never

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "512Mi"
  restartPolicy: Never

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod3
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "512Mi"
  restartPolicy: Never